language: node_js

sudo: false

notifications:
  email:
  - yiminghe@gmail.com

branches:
  only:
    - master

node_js:
  - 16.13.1

before_install:
  - corepack enable

script:
- |
  if [ "$TEST_TYPE" = test ]; then
    npm test
  else
    npm run $TEST_TYPE
  fi
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=browser-test
  - TEST_TYPE=browser-test-cover